name: Greet Contributor

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.SUPERSECRET }}
          issue-message: 'Thanks for helping us make this project better'
          pr-message: 'Thank you for submitting your first PR'